---
version: "3.7"

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
      network: ${NETWORK:-default}
    volumes:
      - tests:/tests
  test:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    network_mode: ${NETWORK:-default}
    command:
      - "/usr/local/bin/start-notebook.sh"
      - "--NotebookApp.token=''"
    ports: [8888:8888]
    environment: [JUPYTER_ENABLE_LAB=true]
    volumes:
      - tests:/share/tests
  inspec:
    image: chef/inspec:current
    network_mode: ${NETWORK:-default}
    environment:
      CHEF_LICENSE: accept-no-persist
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tests:/share/tests:ro

volumes:
  tests:
