---
name: Allspark Build & Test

"on":
  pull_request:
    paths: ["allspark-notebook/**", ".github/workflows/allspark-notebook.yml"]
  push:
    branches: [main]
    paths: ["allspark-notebook/**"]
    tags: '*'

defaults:
  run:
    working-directory: ./allspark-notebook

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@master

  docker:
    runs-on: [self-hosted, ministryofjustice]
    env:
      REPOSITORY: allspark-notebook
      ECR_REPOSITORY: allspark-notebook
    needs: [mdl, yamllint]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ steps.login-ecr.outputs.registry }}
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build image
        run: make build
        env:
          NETWORK: host
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: test
      - name: Install InSpec
        uses: actionshub/chef-install@master
        with:
          channel: current
          project: inspec
      - name: Test
        run: make test
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: test
      - name: Push image
        run: make push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: test
      - name: Cleanup
        if: ${{ always() }}
        run: make clean
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: test
