---
name: Test and Build

on:
  pull_request:
    branches:
      - main

permissions: {} # yamllint disable-line

jobs:
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run yamllint
        id: run_yamllint
        uses: actionshub/yamllint@b772a30c3ba90c5f5aadfe94d8f3599e3a7099c8 # v1.8.2

  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run mdl
        id: run_mdl
        uses: actionshub/markdownlint@6c82ff529253530dfbf75c37570876c52692835f # v3.1.4

  build-and-test:
    if: github.ref != 'main'
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        flavour:
          - "allspark-notebook"
          - "datascience-notebook"
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build and Test
        id: build_and_test
        shell: bash
        run: |
          bash scripts/build-and-test.sh "${{ matrix.flavour }}"
