---
name: Docker Test & Build

"on":
  pull_request:
  push:
    branches: [master]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run yaml Lint
        uses: actionshub/yamllint@master

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@master

  docker:
    needs: [mdl, yamllint]
    runs-on: ubuntu-latest
    env:
      working-directory: ./datascience-notebook
    steps:
      - uses: actions/checkout@v2
      # Disable building until we have a clean Conda install
      # - name: Build
      #   run: make build
      #   working-directory: ${{env.working-directory}}
      - name: Install Inspec
        uses: actionshub/chef-install@1.1.0
        with:
          project: inspec
      - name: Test
        run: make test
        working-directory: ${{env.working-directory}}
        env:
          CHEF_LICENSE: accept-no-persist
