---
name: Datascience Build & Test

"on":
  pull_request:
    paths: ["datascience-notebook/**"]
  push:
    branches: [master]
    paths: ["datascience-notebook/**"]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      working-directory: ./oracle-datascience-notebook
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
        working-directory: ${{env.working-directory}}
      - name: Install Inspec
        uses: actionshub/chef-install@1.1.0
        with: { project: inspec }
      - name: Test
        run: make test
        working-directory: ${{env.working-directory}}
        env: { CHEF_LICENSE: accept-no-persist }
